name: hello world
on: push
jobs:
  my-job:
     my-job:
        runs-on: ubuntu-latest
        steps:
            -name: my-steps
            run: echo "Hello world!"
            name: second-step
            run: "hello again!"